name = "crossbar"
description = "Experimental data validation library in pure Gleam"
docs_url = "https://hexdocs.pm/crossbar/"
repo_url = "https://github.com/aosasona/crossbar"
category = "Validation"
